export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";
export const FETCH_CHANNELS = "FETCH_CHANNELS";
export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const CREATE_CHANNEL = "CREATE_CHANNEL";
export const POST_MESSAGE = "POST_MESSAGE";
export const SET_MESSAGES_LOADING = "SET_MESSAGES_LOADING";
